[package]
version = "0.1.0"
category = "isaaclab"
readme = "README.md"
title = "allex_rl_dexblind"
author = "IRIM"
maintainer = "IRIM"
description = "ALLEX + Dexblind RL task with Newton physics"
repository = "https://github.com/KJG97/IRIM_Newton.git"
keywords = ["extension", "isaaclab", "newton", "allex", "dexblind"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_newton" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "allex_rl_dexblind"
